<div class="header-style-3">
<div class="header-container">
    <div class="header">
		<div class="header-inner">
			<div class="header-top">
				<div class="container">
					<div class="row">
						<div class="col-lg-6 col-md-5  col-sm-6  header-topleft hidden-xs">
							<div class="topleft-content">
								<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('contact-header')->toHtml(); ?>
							</div>
						</div>		

						<div class="col-lg-6 col-md-7 col-sm-6 header-topright">							
							<?php echo $block->getChildHtml('language-header'); ?>	
							<?php echo $block->getChildHtml('currency-header'); ?>			
							<div class="dropdown-block-custom block-myacount">
								<div class="dropdown-toggle">
									<a class="help-link" title="<?php echo __('My Account');?>"><?php echo __('My Account');?></a>
								</div>
								<ul class="dropdown-list">
									<li class="mn-my-account"><a class="myaccount-link" href="<?php echo $block->getUrl('customer/account'); ?>" title="<?php echo __('My Account');?>"><?php echo __('My Account');?></a></li>							
									<li class="mn-top-link-checkout"><a class="top-link-checkout" href="<?php echo $block->getUrl('checkout')?>" title="<?php echo __('Checkout');?>"><?php echo __('Checkout');?></a></li>
									<li class="my-wishlist"><a  href="<?php echo $block->getUrl('wishlist')?>" title="<?php echo __('My Wishlist');?>"><?php echo __('My Wishlist');?></a></li>
									<?php 
									$login_customer = $block->getLayout()->createBlock('Magento\Customer\Block\Account\Customer');
									if ($login_customer->customerLoggedIn()) { ?>
									   <li class="mn-logout"><a href="<?php echo $block->getUrl('customer/account/logout')?>" title="<?php echo __('Logout');?>"><?php echo __('Logout');?></a></li>
									<?php }else { ?>
									<li class="mn-login"><a class="popup-login" href="<?php echo $block->getUrl('customer/account/login')?>" title="<?php echo __('Login')?>"><?php echo __('Login')?></a></li>										
									<?php }
									?>

								</ul>							
							</div>	
							<?php 
								$login_customer = $block->getLayout()->createBlock('Magento\Customer\Block\Account\Customer');
									if ($login_customer->customerLoggedIn()) { ?>
									   <div class="logout custom"><a href="<?php echo $block->getUrl('customer/account/logout')?>" title="<?php echo __('Logout');?>"><?php echo __('Logout');?></a></div>
									<?php }else { ?>
									<div class="login custom"><a class="popup-login" data-toggle="modal" data-target="#modal-login"  href="#"><?php echo __('Login')?></a></div>										
									<?php }
							?>		
						</div>
					</div>
				</div>
			</div>
			<div class="header-middle">
				<div class="container">
					<div class="row">
					   <div class="col-md-3 col-sm-4 col-xs-12">
							<?php echo $block->getChildHtml('logo-header'); ?>	
					   </div>
					   <div class="col-md-9 col-sm-8 warpper-search">
					    	
						 	<div class="search-form-action">
								<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('search-box')->toHtml();?>
							</div>
								
								
					   </div>
					</div>
				</div>
			</div>	
			<div class="header-bottom">
				<div class="container">
				<div class="headerbt-wrapper">
					<div class="row">
						 <div class="col-md-3">
							 <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('vertical-menu-config')->toHtml(); ?>
						 </div>
						 <div class="col-md-9 inner-search">
						 	<div class="menu-cart">
					   			<div class="yt-menu">
									<div class="menu-under">					
										<div class="navigation-container <?php ($_config->getGeneral('menu_style') == 'megamenu') ? "":" css-menu-wrap"; ?>">
											<?php
												if($_config->getGeneral('menu_style') == 'megamenu'){
													echo $block->getChildHtml('navigation-header-megamenu');
												} else {
													echo $block->getChildHtml('navigation-header');
												}
											?>
											<div class="navigation-mobile-container">
												<?php echo $block->getChildHtml('navigation.mobile'); ?>
											</div>
										</div>
									</div>
								</div>
								<?php echo $block->getChildHtml('cart-header'); ?>
							</div>
						 </div>
					</div>
				</div>
				</div>
			</div>
		</div>
	</div>
</div>
</div>