<div class="header-container header-style-5">
  <div class="container">
  <div class="row">
	<div class="pull-left col-md-2 col-sm-3">
	<?php echo $block->getChildHtml('logo-header'); ?>
	</div>
	<div class="col-md-7 col-sm-4 wrapper-menu">
		<div class="mainmenu">
				<div class="navigation-container <?php ($_config->getGeneral('menu_style') == 'megamenu') ? "":" css-menu-wrap"; ?>">
						<?php
							if($_config->getGeneral('menu_style') == 'megamenu'){
								echo $block->getChildHtml('navigation-header-megamenu');
							} else {
								echo $block->getChildHtml('navigation-header');
							}
						?>
					<div class="navigation-mobile-container">
						<?php echo $block->getChildHtml('navigation.mobile'); ?>
					</div>
				</div>

		</div>
	</div>
	<div class="pull-right  col-md-3 col-sm-5">
			<div class="dropdown-block block-topsetting icon-action-top">
				<div class="dropdown-toggle">
					<i class="fa fa-reorder"></i>
				</div>
				<div class="dropdown-list-setting">
					<?php echo $block->getChildHtml('currency-header'); ?>						
					<?php echo $block->getChildHtml('language-header'); ?>
					<ul>
						<li class="mn-my-account"><a class="myaccount-link" href="<?php echo $block->getUrl('customer/account'); ?>" title="<?php echo __('My Account');?>"><?php echo __('My Account');?></a></li>
						<li class="mn-my-wishlist"><a class="my-wishlist" href="<?php echo $block->getUrl('wishlist')?>" title="<?php echo __('My Wishlist');?>"><?php echo __('My Wishlist');?></a></li>
						<li class="mn-top-link-checkout"><a class="top-link-checkout" href="<?php echo $block->getUrl('checkout')?>" title="<?php echo __('Checkout');?>"><?php echo __('Checkout');?></a></li>
						<?php 
						$login_customer = $block->getLayout()->createBlock('Magento\Customer\Block\Account\Customer');
						if ($login_customer->customerLoggedIn()) { ?>
						<li class="mn-logout"><a class="popup-login" href="<?php echo $block->getUrl('customer/account/logout')?>" title="<?php echo __('Logout');?>"><?php echo __('Logout');?></a></li>
						<?php }else { ?>
						<li class="mn-login"><a class="popup-login" href="<?php echo $block->getUrl('customer/account/login')?>" title="<?php echo __('Login')?>"><?php echo __('Login')?></a></li>										
						<?php }
						?>
					</ul>
				</div> 
		</div>
		<div class="icon-action-top"><?php echo $block->getChildHtml('cart-header'); ?></div>
		<div class="header-search5 icon-action-top">
			<div class="icon-search"><i class="fa fa-search"></i></div>
			<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('search-box')->toHtml();?>
		</div>
	</div>	
	</div>
</div>
</div>
<script type="text/javascript">

	require(['jquery'], function ($) {
		$( ".icon-search" ).click(function() {
		$('.sm-searchbox').slideToggle(200);
		$(this).toggleClass('active');
		});
	});
	require(['jquery'], function ($) {
		$( ".header-style-5 .block-topsetting.icon-action-top .dropdown-toggle" ).click(function() {
		$('.header-style-5 .dropdown-list-setting').slideToggle(200);
		$(this).toggleClass('active');
		});
	});
</script>
