<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<div class="block block-subscribe">
    <div class="title-home">
        <h2><?php echo __('newsletter') ?></h2>
    </div>
	<div class="block-content">
		<div class="desc"><?php echo __('Sign up for the latest fashion news, inspiration and upcoming special offers') ?></div>
		 <form class="form subscribe"
            novalidate
            action="<?php /* @escapeNotVerified */ echo $block->getFormActionUrl() ?>"
            method="post"
            data-mage-init='{"validation": {"errorClass": "mage-error"}}'
            id="newsletter-home-validate-detail">
				
				<div class="input-box">
					  <input name="email" type="email" id="newsletter-home"
                                placeholder="<?php /* @escapeNotVerified */ echo __('Enter your email address') ?>"
                                data-validate="{required:true, 'validate-email':true}"/>
                      
                       <button class="action subscribe primary" title="<?php /* @escapeNotVerified */ echo __('Submit') ?>" type="submit">
							<span><?php /* @escapeNotVerified */ //echo __('Submit') ?></span>
						</button>
					
				</div>

				
		</form>
		
	</div>
</div>

