<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>

<div class="container">
<div class="block-subscribe-footer row">
<div class="col-lg-7 col-md-7">
    <div class="block-content">
   <form class="form subscribe"
            novalidate
            action="<?php /* @escapeNotVerified */ echo $block->getFormActionUrl() ?>"
            method="post"
            data-mage-init='{"validation": {"errorClass": "mage-error"}}'
            id="newsletter-validate-detail">
			
            <div class="input-box">
               <input name="email" type="email" id="newsletter"
                                placeholder="<?php /* @escapeNotVerified */ echo __('Enter your email address') ?>"
                                data-validate="{required:true, 'validate-email':true}"/>
               
            </div>
            <div class="actions">
             <button class="action subscribe primary" title="<?php /* @escapeNotVerified */ echo __('Subscribe') ?>" type="submit">
                    <i class="fa fa-send" aria-hidden="true"></i>
                 </button>
            </div>   
            
    </form>
    </div>
</div>
<div class="no-padding col-lg-5 col-md-5">
<div class="title-block">
       <h2> <?php echo __('Sign Up for Our Newsletter ') ?></h2>
        <p><?php echo __('Receive email-only deals, special offers & product exclusives') ?></p>
</div>
</div>
</div>
</div>


