<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<div class="block-subscribe-footer row">
<div class="title-block col-md-5">
       <h2> <?php echo __('Subscribe to Newsletter') ?></h2>
        <p><?php echo __('Receive email-only deals, special offers & product exclusives') ?></p>
</div>
    <div class="block-content col-md-7">
    <form class="form subscribe"
            novalidate
            action="<?php /* @escapeNotVerified */ echo $block->getFormActionUrl() ?>"
            method="post"
            data-mage-init='{"validation": {"errorClass": "mage-error"}}'
            id="newsletter-footer-validate-detail">
            <div class="input-box">
                 <input name="email" type="email" id="newsletter-footer"
                                placeholder="<?php /* @escapeNotVerified */ echo __('Enter your email address') ?>"
                                data-validate="{required:true, 'validate-email':true}"/>
               
            </div>
            <div class="actions">
             <button class="action subscribe primary" title="<?php /* @escapeNotVerified */ echo __('Subscribe') ?>" type="submit">
                    <span><?php  echo __('Subscribe') ?></span>
                 </button>
            </div>   
            
    </form>
    </div>

</div>


