<?php
/**
 *
 * SM Listing Tabs - Version 2.5.0
 * Copyright (c) 2017 YouTech Company. All Rights Reserved.
 * @license - Copyrighted Commercial Software
 * Author: YouTech Company
 * Websites: http://www.magentech.com
 */
 
use Magento\Framework\App\Action\Action;

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Product list template
 *
 * @var $block \Magento\Catalog\Block\Product\ListProduct
 */
?>
<?php
$_config = $this->helper('Sm\ShoppyStore\Helper\Data');

if ($this->_isAjax()) {
	$products = $this->_ajaxLoad();
	$config = $this->_getConfig();
}else{
	$config = $this->getData('config');
	$products = $this->getData('products');
}			
$_helper = $this->helper('Magento\Catalog\Helper\Output');
$viewMode = 'grid';
$img_rec = $config['img_rec'];
if($img_rec){
	$image = 'category_page_grid_rec';
} else {
	$image = 'category_page_grid';
}

$showDescription = false;
$templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;

$type_loadmore = $config['type_show'] == 'loadmore' ? true : false;
$cls_mark = $type_loadmore ? ' ltabs-mark ' : '';
$nb_rows = $config['nb_rows'];
$count = count($products);
$i = 0;
    
    /**
     * Position for actions regarding image size changing in vde if needed
     */
    $pos = $block->getPositioned();
    ?>
    <div class=" <?php /* @escapeNotVerified */ echo $viewMode; ?> ">
        <?php $iterator = 1; ?>
        <div class="products-grid products list items product-items  <?php echo $type_loadmore == false ? ' owl-carousel ' : ''; ?>"  <?php echo $type_loadmore ?  'data-liffect="fadeIn"' : '' ;?>>
            <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
            <?php foreach ($products as $_product): 
				$i++;
			?>
				<?php if($i % $nb_rows == 1 || $nb_rows == 1) { ?>
                <div class="item product product-item <?php echo $cls_mark; ?>">
				<?php } ?>
					<div class="item-inner style1">
						<?php
						$productImage = $block->getImage($_product, $image);
						if ($pos != null) {
							$position = ' style="left:' . $productImage->getWidth() . 'px;'
								. 'top:' . $productImage->getHeight() . 'px;"';
						}
						?>
						<?php
						if ((int)$config['display_countdown'] && !empty($_product->getSpecialPrice()) && !empty($_product->getSpecialToDate())) { 
							$specialToDate = $_product->getSpecialToDate();
						?>
						<div class="deals-countdown" data-timer="<?php echo date("Y/m/d H:i:s", strtotime($specialToDate)); ?>">
							<div class="deals-time time-day"><div class="num-time"></div><div class="title-time"></div></div>
							<div class="deals-time time-hours"><div class="num-time"></div><div class="title-time"></div></div>
							<div class="deals-time time-mins"><div class="num-time"></div><div class="title-time"></div></div>
							<div class="deals-time time-secs"><div class="num-time"></div><div class="title-time"></div></div>
						</div>
						<?php }?>
						<?php // Product Image ?>
						<div class="box-image">
							<a href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
								<?php echo $productImage->toHtml(); ?>
							</a>
							
							<div class="action-bottom">
								<?php if($_config->getAdvanced('show_addtocart_button')){?>
									<?php if ($_product->isSaleable()): ?>
										<?php $postParams = $block->getAddToCartPostParams($_product); ?>
										<form data-role="tocart-form" action="<?php /* @escapeNotVerified */ echo $postParams['action']; ?>" method="post">
											<input type="hidden" name="product" value="<?php /* @escapeNotVerified */ echo $postParams['data']['product']; ?>">
											<input type="hidden" name="<?php /* @escapeNotVerified */ echo Action::PARAM_NAME_URL_ENCODED; ?>" value="<?php /* @escapeNotVerified */ echo $postParams['data'][Action::PARAM_NAME_URL_ENCODED]; ?>">
											<input type="hidden" name="form_key" value="<?php echo $block->_getFormKey(); ?>" />
											<button type="submit"
													title="<?php echo $block->escapeHtml(__('Add to Cart')); ?>"
													class="action tocart primary btn-action btn-cart">
												<span><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
											</button>
										</form>
									<?php else: ?>
										<?php if ($_product->getIsSalable()): ?>
											<div class="stock available"><span><?php /* @escapeNotVerified */ echo __('In stock') ?></span></div>
										<?php else: ?>
											<div class="stock unavailable"><span><?php /* @escapeNotVerified */ echo __('Out of stock') ?></span></div>
										<?php endif; ?>
									<?php endif; ?>
								<?php } ?>
								
								<?php if($_config->getAdvanced('show_wishlist_button')){?>
									<a href="#" class="action towishlist btn-action link-wishlist" title="<?php echo $block->escapeHtml(__('Wishlist')); ?>"  aria-label="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>" data-post='<?php /* @escapeNotVerified */ echo $block->getAddToWishlistParams($_product); ?>' data-action="add-to-wishlist"  role="button">
										<span><?php /* @escapeNotVerified */ echo __('Add to Wish List') ?></span>
									</a>
								<?php } ?>
								
								<?php if($_config->getAdvanced('show_compare_button')){?>
									<?php
										$compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare');
									?>
									<a href="#"  class="action tocompare btn-action link-compare" title="<?php echo $block->escapeHtml(__('Compare')); ?>" aria-label="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"  data-post='<?php /* @escapeNotVerified */ echo $compareHelper->getPostDataParams($_product); ?>' role="button">
										<span><?php /* @escapeNotVerified */ echo __('Add to Compare') ?></span>
									</a>
								<?php } ?>
							</div>
						</div>
						
						<div class="box-info">
							<?php
								$_productNameStripped = $block->stripTags($_product->getName(), null, true);
							?>
							<h2 class="product-name">
								<a class="product-item-link"
								   href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>">
									<?php /* @escapeNotVerified */ echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>
								</a>
							</h2>
							
							<div class="bs-review">
								<?php echo $block->getReviewsSummaryHtml($_product, $templateType, true); ?>
							</div>
							
							<?php /* @escapeNotVerified */ echo $block->getProductPrice($_product) ?>
							<?php echo $block->getProductDetailsHtml($_product); ?>
						</div>
					</div>
				<?php if($i % $nb_rows == 0 || $i == $count) { ?>
                </div>
				<?php } ?>
            <?php endforeach; ?>
        </div>
    </div>
