<?php echo $block->getLayout()->createBlock('Magento\Customer\Block\Form\Login')->setTemplate('Magento_Customer::form/mini.login.phtml')->toHtml(); ?>
<div class="footer-style1">
<div class="footer">	
		<div class="subscribe-footer">
			<?php echo $block->getLayout()->createBlock('Magento\Newsletter\Block\Subscribe')->setTemplate('Magento_Newsletter::subscribe-footer.phtml')->toHtml(); ?>
		</div>
		<div class="footer-top">
			<div class="container">
				<div class="row">
					<div class="col-md-9">
							<div class="col-lg-3 col-md-3 col-sm-6 col-footer account-block">
								<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('ft-account-block')->toHtml(); ?>
							</div>						
							<div class="col-lg-3 col-md-3 col-sm-6 col-footer ft-infomation-block">
								
								<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('ft-infomation-block')->toHtml(); ?>
							</div>
							<div class="col-lg-3 col-md-3 col-sm-6 col-footer corporate-block">
								<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('ft-corporate-block')->toHtml(); ?>
							</div>
							<div class="col-lg-3 col-md-3 col-sm-6 col-footer choose-block">
								<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('ft-choose-block')->toHtml(); ?>
							</div>
					</div>
					<div class="col-md-3">
							<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('ft-contact-us')->toHtml(); ?>
					</div>
					
					
				</div>

			</div>
		</div>
		<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('ft-boxsevicer')->toHtml(); ?>
		<div class="footer-bottom">
			<div class="container">
				<div class="row">
					<div class="col-lg-12 col-md-12 footer-bottom-tag">
						<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('ft-tags-popular')->toHtml(); ?>
					</div>
				</div>
			</div>
		</div>
		<div class="copyright">
			<div class="container">
				<div class="footer-copyright-content">
					<div class="row">
						<div class="col-lg-6 col-md-7 col-sm-6">
							<div class="copyright-footer">
								<?php if($_config->getAdvanced('custom_copyright')){ ?>
									<address><?php echo $_config->getAdvanced('copyright_content') ?></address>
								<?php } else {?>
									<address><?php /* @escapeNotVerified */ echo $block->getCopyright() ?></address>
								<?php } ?>
							</div>
						</div>
						
						<div class="col-lg-6 col-md-5 col-sm-6">
							<div class="payment-footer">
								<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('payment-footer')->toHtml(); ?>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>	