<div class="footer-style2">
<div class="footer">
		<div class="subscribe-footer">
			<div class="container">
			 <div class="row">
			 	<div class="col-md-9">
						<?php echo $block->getLayout()->createBlock('Magento\Newsletter\Block\Subscribe')->setTemplate('Magento_Newsletter::subscribe-footer2.phtml')->toHtml(); ?>
				</div>
				<div class="col-md-3">	
					<div class="social-footer">
						<?php echo $block->getLayout()->createBlock('Magento\Framework\View\Element\Template')->setTemplate('Magento_Theme::html/social.phtml')->toHtml(); ?>
					</div>
				</div>
				</div>
			</div>
		</div>
		
		<div class="footer-top">
			<div class="container">
				<div class="row">
					<div class="col-md-3">
							<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('ft-contact-us')->toHtml(); ?>
							<div class="payment-footer">
								<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('payment-footer')->toHtml(); ?>
							</div>
					</div>
					<div class="col-md-9">
							<div class="col-lg-3 col-md-3 col-sm-6 col-footer account-block">
								<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('ft-account-block')->toHtml(); ?>
							</div>						
							<div class="col-lg-3 col-md-3 col-sm-6 col-footer ft-infomation-block">
								
								<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('ft-infomation-block')->toHtml(); ?>
							</div>
							<div class="col-lg-3 col-md-3 col-sm-6 col-footer corporate-block">
								<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('ft-corporate-block')->toHtml(); ?>
							</div>
							<div class="col-lg-3 col-md-3 col-sm-6 col-footer choose-block">
								<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('ft-choose-block')->toHtml(); ?>
							</div>
					</div>
					
					
					
				</div>

			</div>
		</div>
	<div class="footer-brand">	<div class="container"><?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('slider-brand')->toHtml(); ?></div></div>
		<div class="footer-bottom">
			<div class="container">
				<div class="row">
					<div class="col-lg-12 col-md-12 footer-bottom-tag">
						<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('ft-tags-popular')->toHtml(); ?>
					</div>
				</div>
			</div>
		</div>
		<div class="copyright">
			<div class="container">
				<div class="footer-copyright-content">
					<div class="row">
						<div class="col-lg-12 col-md-12 col-sm-12">
							<div class="copyright-footer">
								<?php if($_config->getAdvanced('custom_copyright')){ ?>
									<address><?php echo $_config->getAdvanced('copyright_content') ?></address>
								<?php } else {?>
									<address><?php /* @escapeNotVerified */ echo $block->getCopyright() ?></address>
								<?php } ?>
							</div>
						</div>
						
						
					</div>
				</div>
			</div>
		</div>
	</div>
</div>	