<div class="footer-style5">
<div class="footer">
	<div class="container">
		<div class="row">
			<div class="col-lg-3 col-md-3 col-sm-4">
				<div class="social-footer">
					<?php echo $block->getLayout()->createBlock('Magento\Framework\View\Element\Template')->setTemplate('Magento_Theme::html/social.phtml')->toHtml(); ?>
				</div>
			</div>
			<div class="col-lg-6 col-md-6 col-sm-5">
					<div class="copyright-footer">
						<?php if($_config->getAdvanced('custom_copyright')){ ?>
							<address><?php echo $_config->getAdvanced('copyright_content') ?></address>
							<?php } else {?>
							<address><?php /* @escapeNotVerified */ echo $block->getCopyright() ?></address>
						<?php } ?>
					</div>
				</div>
			<div class="col-lg-3 col-md-3 col-sm-3">
				<div class="payment-footer">
					<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('payment-footer')->toHtml(); ?>
				</div>
			</div>
		</div>
	</div>
</div>
</div>	

		
		