<div class="footer-style3">
	<div class="footer">
	 	<div class="footer-top">
			<div class="container">
				<div class="row">
					<div class="col-sm-6">
						<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('ft-links-bottom')->toHtml(); ?>
					</div>
					<div class="col-sm-6">
						<div class="social-footer">
							<?php echo $block->getLayout()->createBlock('Magento\Framework\View\Element\Template')->setTemplate('Magento_Theme::html/social.phtml')->toHtml(); ?>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
