<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/* @var $block \Magento\Catalog\Block\Product\AbstractProduct */
?>

<?php
$_config = $this->helper('Sm\ShoppyStore\Helper\Data');
$limit_product = $_config->getProductDetail('related_limit');

switch ($type = $block->getType()) {

    case 'related-rule':
        if ($exist = $block->hasItems()) {
            $type = 'related';
            $class = $type;

            $image = 'related_products_list';
            $title = __('Related Products');
            $items = $block->getAllItems();
            $limit = $block->getPositionLimit();
            $shuffle = (int) $block->isShuffled();

            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;

        }
    break;

    case 'related':
        /** @var \Magento\Catalog\Block\Product\ProductList\Related $block */
        if ($exist = $block->getItems()->getSize()) {
            $type = 'related';
            $class = $type;

            $image = 'related_products_list';
            $title = __('Related Products');
            $items = $block->getItems();
            $limit = 0;
            $shuffle = 0;

            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;

        }
    break;

    case 'other':
    break;
}
?>

<?php if ($exist):?>
    <div class="block product-details box-related">
        <div class="title">
            <strong><?php echo __('Related Products')?></strong>
        </div>
        <div class="related-block products-grid">
            <ol class="products list items product-items">
                <?php $i=0; foreach ($items as $_item): $i++;?>
				<li class="item product product-item">
					<div class="product-item-info">
						<div class="item-inner">
							<div class="box-image">
								<a href="<?php /* @escapeNotVerified */ echo $block->getProductUrl($_item) ?>" class="product photo product-item-photo">
									<?php echo $block->getImage($_item, $image)->toHtml(); ?>
								</a>
								
							</div>
							
							<div class="product details product-item-details box-info">
								<?php echo $block->getReviewsSummaryHtml($_item, $templateType,true) ?>
								<h2 class="product name product-item-name product-name">
									<a class="product-item-link" title="<?php echo $block->escapeHtml($_item->getName()) ?>" href="<?php /* @escapeNotVerified */ echo $block->getProductUrl($_item) ?>">
										<?php echo $block->escapeHtml($_item->getName()) ?>
									</a>
								</h2>

								<?php /* @escapeNotVerified */ echo $block->getProductPrice($_item); ?>

							</div>
						</div>
					</div>
                </li>
				<?php if($i == $limit_product) break;?>
                <?php endforeach ?>
            </ol>
        </div>
          </div>
<?php endif;?>
