<?php
/*------------------------------------------------------------------------
# SM Basic Products - Version 2.1.0
# Copyright (c) 2015 YouTech Company. All Rights Reserved.
# @license - Copyrighted Commercial Software
# Author: YouTech Company
# Websites: http://www.magentech.com
-------------------------------------------------------------------------*/
use Magento\Framework\App\Action\Action;
$list = $block->_getSelectSource();
$helper = $this->_helper();
$nb_column1 = $this->_getConfig('nb_column1', 4);
$nb_column2 = $this->_getConfig('nb_column2', 3);
$nb_column3 = $this->_getConfig('nb_column3', 2);
$nb_column4 = $this->_getConfig('nb_column4', 1);
$nb_column5 = $this->_getConfig('nb_column5', 1);
if (!empty($list)) { 
	$uniqued = 'sm_basic_products_' . time() . rand();
?>
<div id="<?php echo $uniqued ?>" class="block slider-basic-style">
   

	<?php if ($this->_getConfig('display_title', 1)) { ?>
		<?php if ($this->_getConfig('title')) { ?>
			<div class="block-title">
				<strong><?php echo $this->_getConfig('title', 'Sm Basic Products'); ?></strong>
			</div>
		<?php } ?>
	<?php } ?>
	 <?php if ($this->_getConfig('pretext') != null) { 
	 	 $pretext = $this->_getConfig('pretext'); 
	 	?>
		<div class="bs-pretext">
			<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId($pretext)->toHtml(); ?>
		</div>
	<?php } ?>
    <div class="products-grid">
        <!-- Begin bs-items     -->
        <div class="bs-items slider-product-index">
            <?php  $j = 0;
            foreach ($list as $_product) { $j++;
                ?>
                <!-- Begin bs-item-cf -->
                <div class="item bs-item cf">
                    <!-- Begin bs-item-inner -->
                    <div class="item-inner style1">
                        <?php if ($_product->_image) { ?>
                            <div class="box-image">
                                <a class="product-image" href="<?php echo $_product->link ?>"
                                   title="<?php echo $_product->title; ?>"
                                    <?php echo $helper->parseTarget($this->_getConfig('target')); ?>
                                    >
                                    <img src="<?php echo $_product->_image; ?>"
                                         title="<?php echo $_product->title; ?>"
                                         alt="<?php echo $_product->title; ?>"
                                        >
                                </a>
								
								<!--LABEL PRODUCT-->
                               
                               <?php
                                $price = $_product->getPrice();
                                $specialprice = $_product->getSpecialPrice();
                                $specialPriceFromDate = $_product->getSpecialFromDate();
                                $specialPriceToDate = $_product->getSpecialToDate();
                                            
                                $today = time();
								if($_product->getSpecialFromDate() && $_product->getSpecialToDate()){
                                if($price){
                                    $sale = round((($price-$specialprice)/$price)*100);
                                

                                if ($specialprice) {
                                if ($today >= strtotime($specialPriceFromDate) && $today <= strtotime($specialPriceToDate) || $today >= strtotime($specialPriceFromDate) && is_null($specialPriceToDate)) { ?>
                                        <div class="label-product label-sale">
                                            <span class="sale-product-icon">
                                                <?php if($sale) { echo '-'.$sale.'%'; } else {echo __('Sale');} ?>
                                            </span>
                                        </div>
                                    <?php }
								} } }
                                ?>
								
								<?php
								$now = date("Y-m-d");
								if($_product->getNewsFromDate() && $_product->getNewsToDate()){
                                $newsFrom = substr($_product->getNewsFromDate(), 0, 10);
                                $newsTo = substr($_product->getNewsToDate(), 0, 10);
								
								if ($newsTo != '' || $newsFrom != '') {
                                    if (($newsTo != '' && $newsFrom != '' && $now >= $newsFrom && $now <= $newsTo) || ($newsTo == '' && $now >= $newsFrom) || ($newsFrom == '' && $now <= $newsTo)) {?>
                                            <div class="label-product label-new">
												<span class="new-product-icon"><?php echo __('New'); ?></span>
											</div>
                                    <?php }
                                } } ?>			
								<!--END LABEL PRODUCT-->
								<div class="action-bottom">
										<?php if ((int)$this->_getConfig('product_addcart_display', 1)) { ?>
												<?php if ($_product->isSaleable()){ ?>
													<?php if ($_product->getTypeInstance()->hasRequiredOptions($_product)){ ?>
														<button class="action tocart btn-cart btn-action" data-mage-init='{"redirectUrl": {"url": "<?php echo $block->getAddToCartUrl($_product) ?>"}}' type="button" title="<?php  echo __('Add to Cart') ?>">
															<span><?php  echo __('Add to Cart') ?></span>
														</button>
													<?php } else { ?>
														<?php $postDataHelper = $this->helper('Magento\Framework\Data\Helper\PostHelper');
														$postData = $postDataHelper->getPostData($block->getAddToCartUrl($_product), ['product' => $_product->getEntityId()])
														?>
														<button class="action tocart btn-cart btn-action"
																data-post='<?php echo $postData; ?>'
																type="button" title="<?php  echo __('Add to Cart') ?>">
															<span><?php echo __('Add to Cart') ?></span>
														</button>
													<?php } ?>
												<?php } else { ?>
													<?php if ($_product->getIsSalable()){ ?>
														<div class="stock available"><span><?php  echo __('In stock') ?></span></div>
													<?php } else { ?>
														<div class="stock unavailable"><span><?php  echo __('Out of stock') ?></span></div>
													<?php } ?>
												<?php } ?>
											<?php } ?>
											<?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow() && (int)$this->_getConfig('product_addwishlist_display', 1) ){ ?>
												<a href="#" class="action towishlist btn-action link-wishlist"  title="<?php echo $block->escapeHtml(__('Wishlist')); ?>"  aria-label="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>" data-post='<?php /* @escapeNotVerified */ echo $block->getAddToWishlistParams($_product); ?>' data-action="add-to-wishlist"  role="button">
                                           					 <span><?php /* @escapeNotVerified */ echo __('Add to Wish List') ?></span>
                                       				 </a>
												
											<?php } ?>
												
											<?php if ($block->getAddToCompareUrl() &&  (int)$this->_getConfig('product_addcompare_display', 1)){ ?>
													<?php
														$compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare');
														?>
									
														<a href="#"  class="action tocompare btn-action link-compare"  title="<?php echo $block->escapeHtml(__('Compare')); ?>" aria-label="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"  data-post='<?php /* @escapeNotVerified */ echo $compareHelper->getPostDataParams($_product); ?>' role="button">
                                        					<span><?php /* @escapeNotVerified */ echo __('Add to Compare') ?></span>
                                    					</a>
												
											<?php }; ?>

										

                            </div>
                            </div>
                        <?php }?>

                        <!-- Begin bs-content -->
                        <?php  ?>
						<div class="product details product-item-details box-info">

							

                            <?php if ((int)$this->_getConfig('product_title_display', 1)) { ?>
                                <h2 class="product name product-item-name product-name">
                                    <a href="<?php echo $_product->link; ?>" title="<?php echo $_product->title; ?>"
                                        <?php echo $helper->parseTarget($this->_getConfig('target')); ?>
                                        >
                                        <?php echo $helper->truncate($_product->title, $this->_getConfig('product_title_maxlength')); ?>
                                    </a>
                                </h2>
                            <?php } ?>
							
							<?php if ((int)$this->_getConfig('product_reviews_count', 1)) {
										$templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
										echo $block->getReviewsSummaryHtml($_product,$templateType ,true); 
							} ?>
							
                                <?php if ((int)$this->_getConfig('product_price_display', 1)) {
									echo $this->getProductPrice($_product);
                                } ?>
								
							
							
                            <?php if ((int)$this->_getConfig('product_description_display', 1) && $helper->_trimEncode($_product->_description) != '') { ?>
                                <div class="bs-description">
                                    <?php echo $_product->_description; ?>
                                </div>
                            <?php } ?>
							
                            <?php if ($this->_getConfig('cat_title_display') == 1 && $this->_getConfig('product_source') != 'media') { ?>
                               <div class="bs-category"><?php echo __('Category:&nbsp') ;?>
									<a  href="<?php echo $_product->cat_link; ?>"  title="<?php echo $_product->cat_title; ?>"  <?php echo $helper->parseTarget($this->_getConfig('target')); ?>>
										 <?php echo  $helper->truncate($_product->cat_title, $this->_getConfig('category_title_max_characs', 25)); ?>
									</a>
									
                                </div>
                            <?php } ?>

								
                            <?php if ($this->_getConfig('product_source') != 'media') { ?>

								<?php if ((int)$this->_getConfig('product_addcart_display', 1) ||(int)$this->_getConfig('product_addwishlist_display', 1) || (int)$this->_getConfig('product_addcompare_display', 1)) { ?>
								<div class="product actions product-item-actions">
									

									
								</div>
								<?php } ?>
                            <?php } ?>

                            <?php if ($this->_getConfig('product_readmore_display') == 1) { ?>
                                <div class="bs-detail">
                                    <a href="<?php echo $_product->link ?>"
                                       title="<?php echo $_product->title; ?>"
                                        <?php echo $helper->parseTarget($this->_getConfig('target')); ?>
                                        >
                                        <?php echo $this->_getConfig('product_readmore_text', 'Details'); ?>
                                    </a>
                                </div>
                            <?php } ?>
                            
							
                        </div>
						
                        <!-- End bs-content -->
                    </div>
                    <!-- End bs-item-inner -->
                </div><!-- End bs-item-cf -->
            <?php } ?>
        </div>
		
		<script>
			require(['jquery','owlcarousel'], function ($, owlCarousel) {
				var bs_slider = $("#<?php echo $uniqued; ?> .slider-product-index");
				bs_slider.owlCarousel({				
					autoplay:false,
					loop:false,
					nav : true, // Show next and prev buttons
					dots: false,
					autoplaySpeed : 500,
					navSpeed : 500,
					dotsSpeed : 500,
					autoplayHoverPause: true,
					margin:30,
					responsive: {
						0: {
							items:1
						},
						480: {
							items:<?php echo $nb_column4;?>
						},
						768: {
							items:<?php echo $nb_column3;?>
						},
						991: {
							items:<?php echo $nb_column2;?>
						},						
						1200: {
							items:<?php echo $nb_column1;?>
						}
					}
				});	  
			});	
		</script>
        <!-- End bs-items -->
    </div><!-- End Sm-basic-products -->
   <?php if ($this->_getConfig('posttext') != null) { ?>
		<div class="bs-posttext">
			<?php echo $this->_getConfig('posttext'); ?>
		</div>
	<?php } ?>
</div>	
<?php
} else {
	echo '<h1 style="color:#f1703d;">Has no content to show!</h1>';
}
?>