<?php
/*------------------------------------------------------------------------
# SM Basic Products - Version 2.1.0
# Copyright (c) 2015 YouTech Company. All Rights Reserved.
# @license - Copyrighted Commercial Software
# Author: YouTech Company
# Websites: http://www.magentech.com
-------------------------------------------------------------------------*/
use Magento\Framework\App\Action\Action;
$list = $block->_getSelectSource();
$helper = $this->_helper();
	
if (!empty($list)) { 
	$uniqued = 'sm_basic_products_' . time() . rand();
?>
<div id="<?php echo $uniqued ?>" class="block slider-basic-product-bottom">
   

	<?php if ($this->_getConfig('display_title', 1)) { ?>
		<?php if ($this->_getConfig('title')) { ?>
			<div class="block-title">
				<strong><?php echo $this->_getConfig('title', 'Sm Basic Products'); ?></strong>
			</div>
		<?php } ?>
	<?php } ?>
	 <?php if ($this->_getConfig('pretext') != null) { ?>
		<div class="bs-pretext">
			<?php echo $this->_getConfig('pretext'); ?>
		</div>
	<?php } ?>
    <div class="products-grid">
        <!-- Begin bs-items     -->
        <div class="bs-items slider-product-index2">
            <?php  $j = 0;
            foreach ($list as $_product) { 
            	 if($j % 2 == 0 ) {
                     echo '<div class="row-item">';
                	 }
                ?>
                <!-- Begin bs-item-cf -->
                <div class="item bs-item cf">
                    <!-- Begin bs-item-inner -->
                    <div class="item-inner">
                        <?php if ($_product->_image) { ?>
                            <div class="box-image">
                                <a class="product-image" href="<?php echo $_product->link ?>"
                                   title="<?php echo $_product->title; ?>"
                                    <?php echo $helper->parseTarget($this->_getConfig('target')); ?>
                                    >
                                    <img src="<?php echo $_product->_image; ?>"
                                         title="<?php echo $_product->title; ?>"
                                         alt="<?php echo $_product->title; ?>"
                                        >
                                </a>
								
								<!--LABEL PRODUCT-->
                               
                               <?php
                                $price = $_product->getPrice();
                                $specialprice = $_product->getSpecialPrice();
                                $specialPriceFromDate = $_product->getSpecialFromDate();
                                $specialPriceToDate = $_product->getSpecialToDate();
                                            
                                $today = time();
								if($_product->getSpecialFromDate() && $_product->getSpecialToDate()){
                                if($price){
                                    $sale = round((($price-$specialprice)/$price)*100);
                                

                                if ($specialprice) {
                                if ($today >= strtotime($specialPriceFromDate) && $today <= strtotime($specialPriceToDate) || $today >= strtotime($specialPriceFromDate) && is_null($specialPriceToDate)) { ?>
                                        <div class="label-product label-sale">
                                            <span class="sale-product-icon">
                                                <?php if($sale) { echo '-'.$sale.'%'; } else {echo __('Sale');} ?>
                                            </span>
                                        </div>
                                    <?php }
								} } }
                                ?>
								
								<?php
								$now = date("Y-m-d");
								if($_product->getNewsFromDate() && $_product->getNewsToDate()){
                                $newsFrom = substr($_product->getNewsFromDate(), 0, 10);
                                $newsTo = substr($_product->getNewsToDate(), 0, 10);
								
								if ($newsTo != '' || $newsFrom != '') {
                                    if (($newsTo != '' && $newsFrom != '' && $now >= $newsFrom && $now <= $newsTo) || ($newsTo == '' && $now >= $newsFrom) || ($newsFrom == '' && $now <= $newsTo)) {?>
                                            <div class="label-product label-new">
												<span class="new-product-icon"><?php echo __('New'); ?></span>
											</div>
                                    <?php }
                                } } ?>			
								<!--END LABEL PRODUCT-->
								
								<div class="bottom-action-out-wrap">
									<div class="bottom-action-out">
										<div class="bottom-action">
											<a style="display: none;" href="<?php echo $_product->link; ?>">&nbsp;</a>
											
											<?php if ((int)$this->_getConfig('product_addwishlist_display', 1) || (int)$this->_getConfig('product_addcompare_display', 1)) { ?>

													<?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow() && (int)$this->_getConfig('product_addwishlist_display', 1) ){ ?>
														<a href="#" data-post='<?php  echo $block->getAddToWishlistParams($_product); ?>'  class="action towishlist btn-action link-wishlist" data-action="add-to-wishlist" title="<?php  echo __('Add to Wish List') ?>">
															<span><?php  echo __('Add to Wish List') ?></span>
														</a>
													<?php } ?>
													
													<?php if ($block->getAddToCompareUrl() &&  (int)$this->_getConfig('product_addcompare_display', 1)){ ?>
														<?php
														$compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare');
														?>
														<a href="#" class="action tocompare btn-action link-compare"
														   data-post='<?php  echo $compareHelper->getPostDataParams($_product);?>'
														   data-role="add-to-links"
														   title="<?php  echo __('Add to Compare'); ?>">
															<span><?php  echo __('Add to Compare') ?></span>
														</a>
													<?php }; ?>
											<?php } ?>
											
										</div>
									</div>
								</div>
                            </div>
                        <?php }?>

                        <!-- Begin bs-content -->
                        <?php  ?>
						<div class="product details product-item-details box-info">

							<?php if ((int)$this->_getConfig('product_reviews_count', 1)) {
										$templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
										echo $block->getReviewsSummaryHtml($_product,$templateType ,true); 
							} ?>

                            <?php if ((int)$this->_getConfig('product_title_display', 1)) { ?>
                                <h2 class="product name product-item-name product-name">
                                    <a href="<?php echo $_product->link; ?>" title="<?php echo $_product->title; ?>"
                                        <?php echo $helper->parseTarget($this->_getConfig('target')); ?>
                                        >
                                        <?php echo $helper->truncate($_product->title, $this->_getConfig('product_title_maxlength')); ?>
                                    </a>
                                </h2>
                            <?php } ?>
							
                            <?php if ((int)$this->_getConfig('product_price_display', 1)) {
								echo $this->getProductPrice($_product);
                            } ?>
								
							
							
                            <?php if ((int)$this->_getConfig('product_description_display', 1) && $helper->_trimEncode($_product->_description) != '') { ?>
                                <div class="bs-description">
                                    <?php echo $_product->_description; ?>
                                </div>
                            <?php } ?>
							
                           
                          
                            <?php if ((int)$this->_getConfig('product_addcart_display', 1)) { ?>
									<?php if ($_product->isSaleable()): ?>
									<?php $postParams = $block->getAddToCartPostParams($_product); ?>
									<form data-role="tocart-form" action="<?php /* @escapeNotVerified */ echo $postParams['action']; ?>" method="post">
										<input type="hidden" name="product" value="<?php /* @escapeNotVerified */ echo $postParams['data']['product']; ?>">
										<input type="hidden" name="<?php /* @escapeNotVerified */ echo Action::PARAM_NAME_URL_ENCODED; ?>" value="<?php /* @escapeNotVerified */ echo $postParams['data'][Action::PARAM_NAME_URL_ENCODED]; ?>">
														<?php echo $block->getBlockHtml('formkey')?>
										<button type="submit" title="<?php echo $block->escapeHtml(__('Add to Cart')); ?>" class="action tocart primary  btn-cart">
											<span><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
										</button>
									</form>
									<?php else: ?>
									<?php if ($_product->getIsSalable()): ?>
										<div class="stock available"><span><?php /* @escapeNotVerified */ echo __('In stock') ?></span></div>
									<?php else: ?>
										<div class="stock unavailable"><span><?php /* @escapeNotVerified */ echo __('Out of stock') ?></span></div>
										<?php endif; ?>
									<?php endif; ?>
							<?php } ?>
							
                        </div>
						
                        <!-- End bs-content -->
                    </div>
                    <!-- End bs-item-inner -->
                </div><!-- End bs-item-cf -->
            <?php
            	$j++;
            	  if($j% 2 == 0 || $j  ==  count($list) ) {
	                    echo '</div>'; // endrow
	                }
             } 
             ?>
        </div>
		
		<script>
			require(['jquery','owlcarousel'], function ($, owlCarousel) {
				var bs_slider = $("#<?php echo $uniqued; ?> .slider-product-index2");
				bs_slider.owlCarousel({				
					responsive:{
						0:{
							items:<?php echo $this->_getConfig('nb_column5', 1); ?>
						},
						480:{
							items:<?php echo $this->_getConfig('nb_column4', 1); ?>
						},
						768:{
							items:<?php echo $this->_getConfig('nb_column3', 3); ?>
						},
						992:{
							items:<?php echo $this->_getConfig('nb_column2', 3); ?>
						},
						1200:{
							items:<?php echo $this->_getConfig('nb_column1', 3); ?>
						}
					},
					autoplay:false,
					loop:false,
					nav : true, // Show next and prev buttons
					dots: false,
					autoplaySpeed : 500,
					navSpeed : 500,
					dotsSpeed : 500,
					autoplayHoverPause: true,
					margin:0,
				});	  
			});	
		</script>
        <!-- End bs-items -->
    </div><!-- End Sm-basic-products -->
   <?php if ($this->_getConfig('posttext') != null) { ?>
		<div class="bs-posttext">
			<?php echo $this->_getConfig('posttext'); ?>
		</div>
	<?php } ?>
</div>	
<?php
} else {
	echo '<h1 style="color:#f1703d;">Has no content to show!</h1>';
}
?>